# Homework 2

## Author: Marusic Diana (331)

**TODO:** You  should  state  and  describe  the  problem  you  are  trying  to  solve.  Describe  thedata  (type  of  data,  summary  statistics),  the  desired  output,  and  the  proposed  model.

In [3]:
# Test
print("Hello world")

Hello world


### Import files 

In [4]:
# Some IPython magic
# Put these at the top of every notebook, here nbagg is used for interactive plots
%reload_ext autoreload
%autoreload 2
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Check python version
# import sys
# print(sys.version)
# print(sys.version_info)

## Task 1: Text classification (by authors)

**TODO:**

- use SVM Classifier(SVC) to predict author. 

 * hyperparameters:  (kernel,  C,  gamma) 
 
 
- apply PCA to reduce dimensionality and retrain

### Read data

In [41]:
FILE_NAME = "Marusic I Diana.csv"
dataset = pd.read_csv(FILE_NAME)

### Visualize data

In [42]:
dataset.head()
# print(dataset)

Unnamed: 0                             Sir Arthur Conan Doyle  \
0           0  efforts of old Gilray in the interests of law ...   
1           1  of accepting the inevitable.  A flat Arab loaf...   
2           2  Commons with an energy of hatred that one woul...   
3           3  to breathe. There it was again! And again! Now...   
4           4  chair, he brewed himself a glass of grog, in w...   

                                    Sir Walter Scott  \
0  wood or stone, but only as emblems of the holy...   
1  was burned alive. Her name was Alison Pearson,...   
2  the assertion, that a king might take a lesson...   
3  I have this day learned more of Duke Charles t...   
4  murdered Countess, while at the same time he d...   

                                   Louisa May Alcott  \
0  of penitence and thankfulness.  "Call them now...   
1  and there was no time to ask leave, but it was...   
2  locks powdered the dark ones.  "A heavenly wal...   
3  let us help you if we can. Are you ill, in wan...   
4  thoughts swept through his mind during a brief...   

                                        Edmund Burke  \
0  formerly received from the Vizier. _But a copy...   
1  for traders and manufacturers of every denomin...   
2  honorable and advantageous to the India Compan...   
3  understand, to be sure, that I speak of Charle...   
4  Dowlah Bahadur, do agree that      the jaghire...   

                                        Daniel Defoe  \
0  musket, I sat down myself to load all the rest...   
1  substantial Matter, which tho' it is full of S...   
2  would not accept of it alone, but would have m...   
3  the slip both together, and never heard more o...   
4  itself, I thought it seemed to lie higher out ...   

                                         John Ruskin  \
0  a stone-mason's yard; and its rooms whitewashe...   
1  instance, the Gothic foliage, of which one ess...   
2  God. To these alone we have to look; in these ...   
3  issue is not understood by the people, and the...   
4  thus to secure a portion of it than none: but ...   

                                     Rudyard Kipling  \
0  once with a Bank of England director; wish I'd...   
1  way. _Time_: The edge of sunset. Single room i...   
2  them. "Fitz is right. I'm dead; only I don't s...   
3  twisted into knots, riven with rents and diamo...   
4  bush-tailed thieves!'  Mother Wolf threw herse...   

                                 Nathaniel Hawthorne  \
0  commander-in-chief of all the British forces i...   
1  feeling of an intruder, I walked towards Goat ...   
2  suppose, and in the winter and spring it will ...   
3  in a religious calm; recollections of many a h...   
4  place of study and retirement.  There was a fa...   

                         William Makepeace Thackeray  \
0  hard-heartedness in order to try those people ...   
1  out blaggerd names at you, and takes his pewny...   
2  those of Parson Thwackum, or Miss Seagrim. But...   
3  papa. I am Number 46 in the Exhibition of the ...   
4  Course! the Course is at Calcutta, papa!" crie...   

                         ...                          \
0                        ...                           
1                        ...                           
2                        ...                           
3                        ...                           
4                        ...                           

                           Edward Phillips Oppenheim  \
0  say, I should have expected to have found her ...   
1  the blowing away of the window was merely a ru...   
2  you, wouldn't it?" Philip remarked.  "Five hun...   
3  making that speech he had departed a great dea...   
4  read a little more of the New Testament and a ...   

                                       P G Wodehouse  \
0  Mr. Peters? Don't you think there is danger he...   
1  cereal and a shirred egg? Now, for the love of...   
2  more about your unfortunate affair with that g...   


Dataset contains: 20 samples of text x ... authors
Each column - header: Author name, row - text


Dataset contains samples  of  text  from  20  different  authors.  Each sample  has  50.000  characters  and  there  are  20  samples  for  each  author.

In [19]:
for i in range(1, len(dataset)):
    print("Author:" + dataset.iloc[:,i].name)
    print(dataset.iloc[:,i])
    print("i=", i)
    print()

Author:Sir Arthur Conan Doyle
0     efforts of old Gilray in the interests of law ...
1     of accepting the inevitable.  A flat Arab loaf...
2     Commons with an energy of hatred that one woul...
3     to breathe. There it was again! And again! Now...
4     chair, he brewed himself a glass of grog, in w...
5     places, I had forgotten about that spot upon t...
6     rather complex, and therefore interesting.  Hi...
7     wanting When the farmer comes to count them in...
8     vituperation.  In one of his outbursts he thre...
9     fact that in the year 1865 a picture by Greuze...
10    in the country. They would suffice to break of...
11    Averroes?"  "No, I have not.  But the appointm...
12    foraging parties which had never returned.  Th...
13    them to the light as he did so. He was clearly...
14    one great brown wrinkled cliff succeeding anot...
15    best."  "I perceive," said the prince, "that y...
16    by immigrants who are far more highly educated...
17    the Royal st

0     Mr. Peters? Don't you think there is danger he...
1     cereal and a shirred egg? Now, for the love of...
2     more about your unfortunate affair with that g...
3     person who thanked goodness that he was not al...
4     suddenly pulled into the conversation, again l...
5     "It was an invigorating time," said Psmith. "A...
6     obtained by bringing happiness to others. Bugs...
7      THE POTHUNTERS     by P. G. Wodehouse  1902  ...
8     were there and you know, of course, but I shou...
9     Reece, laying down his pen and turning round i...
10    his finer feelings. But he has seen me only on...
11    limbs were clad in what I put down as a mail-o...
12    soda the gulf between non-acquaintance and war...
13    realized by this time that he was a good long ...
14    a jolly good screw and a ripping open-air life...
15    granted her.  "Uncle Chris thinks so," she sai...
16    frightfully pretty girl with gold hair. If you...
17    result of climbing three flights of stairs

0     stood by the open door, Martin, a helmet from ...
1     it must be supreme. For this ornament was noth...
2     gate of the kraal. But then her strength left ...
3     known who was sentenced to death by the Inquis...
4     Thither we went up the sides of the steep pyra...
5     which caught his practised eye, had cast away ...
6     land of Goshen to fulfil the commands of Phara...
7     past years and speak their language; and that ...
8     He is not such a bad sort of man, and he is we...
9     crossing a couple of wheat fields came to a su...
10    their dark cloaks, they rode down to the highw...
11    regards what I interpret as fastidiousness, th...
12    see, and by means of my rifle to assist in, th...
13    do they talk?"  "They--are--friends of mine," ...
14    noted with a pang that as they went the lady B...
15    something else."  "What else, Rachel?"  "Do yo...
16    Elissa? Well, she must die--if this was not a ...
17    must first be lifted up above the world. H

### Import dictionary of English words

In [20]:
# creates a wordlist, with all words, from "a" to "zygote"
import urllib.request as request
words = request.urlopen("https://svnweb.freebsd.org/csrg/share/dict/words?view=co")
wordlist = []
for w in words:
    wordlist.append(str(w.decode().strip()))
print(', '.join(wordlist[:4]) + " ... " + ', '.join(wordlist[-4:]))

a, AAA, AAAS, aardvark ... zucchini, Zulu, Zurich, zygote


In [7]:
print("Now we can convert any text to a vector of size " \
      + str(len(wordlist)))

Now we can convert any text to a vector of size 25487


### Using CountVectorizer

In [39]:
#TO DO: Transfrom the dataset into numerical feature vectors
from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer()

i = 1
# for i in range(1, len(dataset)):
print("Author:" + dataset.iloc[:,i].name)
#     print(dataset.iloc[:,i])
print("i=", i)
print()

X = vectorizer.fit_transform(dataset.iloc[:,i])
# print(X[:,len(X)-1])
print(X)
print(X.toarray())

#     plt.hist(X[0], X[1])
#     plt.plot(X[0], X[1])

Author:Sir Arthur Conan Doyle
i= 1

  (0, 31500)	1
  (0, 32745)	1
  (0, 31659)	1
  (0, 4534)	1
  (0, 9373)	1
  (0, 15437)	1
  (0, 30868)	1
  (0, 8820)	1
  (0, 8331)	1
  (0, 27120)	1
  (0, 25872)	1
  (0, 27355)	1
  (0, 32684)	1
  (0, 34990)	1
  (0, 17399)	1
  (0, 21962)	1
  (0, 12945)	1
  (0, 12628)	1
  (0, 6491)	1
  (0, 18479)	1
  (0, 33825)	1
  (0, 17739)	1
  (0, 26722)	1
  (0, 32747)	1
  (0, 15340)	1
  :	:
  (19, 26853)	79
  (19, 14464)	10
  (19, 7976)	12
  (19, 22240)	118
  (19, 14065)	8
  (19, 14598)	24
  (19, 35149)	683
  (19, 21747)	2
  (19, 22021)	322
  (19, 10162)	3
  (19, 32859)	166
  (19, 5158)	420
  (19, 2168)	8
  (19, 34530)	1327
  (19, 17658)	11
  (19, 20964)	264
  (19, 22147)	43
  (19, 1856)	2443
  (19, 18449)	19
  (19, 17101)	3
  (19, 31586)	5634
  (19, 16507)	1583
  (19, 21968)	72
  (19, 21907)	2772
  (19, 10821)	7
[[ 0  0  0 ...  0  0  0]
 [ 3  0  2 ...  0  0  0]
 [ 2  0  1 ...  0  0  0]
 ...
 [ 0  0  1 ...  0  0  0]
 [ 0  0  2 ...  0  0  0]
 [11  1  6 ...  0  0  0]]


In [32]:
!pip3 install yellowbrick
from yellowbrick.text import FreqDistVisualizer


    100% |████████████████████████████████| 286kB 2.8MB/s ta 0:00:01
    100% |████████████████████████████████| 12.6MB 546kB/s ta 0:00:01  3% |█                               | 419kB 5.9MB/s eta 0:00:03    81% |██████████████████████████▏     | 10.3MB 2.8MB/s eta 0:00:01
  Found existing installation: matplotlib 3.0.2
    Uninstalling matplotlib-3.0.2:
      Successfully uninstalled matplotlib-3.0.2


In [33]:
vectorizer = CountVectorizer()
docs       = vectorizer.fit_transform(dataset.iloc[:,i])
features   = vectorizer.get_feature_names()

visualizer = FreqDistVisualizer(features=features)
visualizer.fit(docs)
visualizer.poof()

[autoreload of matplotlib failed: Traceback (most recent call last):
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 376, in superreload
    module = reload(module)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_

[autoreload of matplotlib.container failed: Traceback (most recent call last):
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 392, in superreload
    update_generic(old_obj, new_obj)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 329, in update_generic
    update(a, b)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 287, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPyt

[autoreload of matplotlib.backends.backend_agg failed: Traceback (most recent call last):
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 392, in superreload
    update_generic(old_obj, new_obj)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 329, in update_generic
    update(a, b)
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 287, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/mdiannna/Machine Learning/MachineLearningHomeworks/Homework2/P3/lib/python3.6/site-pa

AttributeError: module 'matplotlib.rcsetup' has no attribute '_auto_backend_sentinel'

## Task 2: Text clustering

**TODO:** Does  the  clustering  gives  you  back  the  books  clustered  by  author?Are  the  books  grouped  differently?  Can  you  find  what  authors  have  similar  writing  styles?Or  are  the  books  grouped  by  genre? 

Unsupervised learning => will need to find something in the dataset and explain what found

**TODO:**
- DBCAN ( *eps*  and  *minsamples* hyperparams)
- KMeans ( *nclusters*  and  *init* hyperparams)
- Hierarchical(Agglomerative)  ( *nclusters* hyperparams)

- compare + metrics:
    *  *silhouette  score*
    * *homogeneityscore*
    * *completness  score*. 

## Bonus

 For  using  clustering  and  dimensionality  reduction  techniqueson  your  first  homework  dataset